version: '3.9'

services:
  bot:
    build: .
    container_name: token-bot
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    tty: true

  db:
    image: postgres:15
    container_name: token-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data